### ISSUE TITLE
Dicaaa

### ISSUE THREAD

**Issue by celenny** [OdilonDamasceno/OdilonDamasceno#1]
### Iae Dev,  encontrei uns repositórios bacanas que podem te ajudar a melhorar teu readme.
- [Badges 4 README](https://github.com/alexandresanlim/Badges4-README.md-Profile)
- [README stats](https://github.com/anuraghazra/github-readme-stats) <br>
![newgame (1)](https://user-images.githubusercontent.com/70456452/105044837-f2f02600-5a45-11eb-8431-16968051aa2c.gif)

**Comment by OdilonDamasceno** [comment]
Opaaaa, muito obrigado pela dica, Celenny. Irei usar agora mesmo <3
